### ISSUE TITLE
Projects: Groups/Roles

### ISSUE THREAD

**Issue by mawiegand** [BluePanel/old-rails-website#23]
After issue #10 

Administer Groups/Roles with specific rights for projects

**Comment by apollo7321** [comment]
Wozu? Könntest du das Issue ein wenig erläutern?

**Comment by mawiegand** [comment]
I updated the description above. I don't know if it is enough for you.

Next time please follow the rules over here [Rules for comments](https://github.com/BluePanel/website/wiki/Rules-for-comments)

**Comment by apollo7321** [comment]
404, doesn't exist.

**Comment by mawiegand** [comment]
The link is working. Maybe something on Github went wrong when you tried it.
