### ISSUE TITLE
Posts from deleted user causing error

### ISSUE THREAD

**Issue by lhannigbrinck** [BluePanel/old-rails-website#46]
Old post from a user which has canceled his account causing errors

**Comment by mawiegand** [comment]
There are two solutions for solving this problem.
First one: Delete all Posts, Topics, etc. of the user
Second one: Change the ownership of old Posts, etc. to "Deleted User" (which needs to be created, if doesn't exists)

**Comment by SStalker** [comment]
I would choose the second one^^
